In [1]:
import pandas as pd
import numpy as np

In [2]:
# !wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

In [3]:
df = pd.read_csv('data.csv')
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
Make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
Model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
Year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
Engine Fuel Type,premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),...,premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (recommended),regular unleaded
Engine HP,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
Engine Cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
Transmission Type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
Driven_Wheels,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,...,rear wheel drive,rear wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,front wheel drive
Number of Doors,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
Market Category,"Factory Tuner,Luxury,High-Performance","Luxury,Performance","Luxury,High-Performance","Luxury,Performance",Luxury,"Luxury,Performance","Luxury,Performance","Luxury,High-Performance",Luxury,Luxury,...,"Exotic,Luxury,High-Performance","Exotic,Luxury,High-Performance","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury",Luxury
Vehicle Size,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,...,Compact,Compact,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize
Vehicle Style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway MPG,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
Popularity,3916,3916,3916,3916,3916,3916,3916,3916,3916,3916,...,3916,3916,204,204,204,204,204,204,204,61
MSRP,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995

In [4]:
used_columns = ['Make',
'Model',
'Year',
'Engine HP',
'Engine Cylinders',
'Transmission Type',
'Vehicle Style',
'highway MPG',
'city mpg',
'MSRP']

df = df[used_columns]
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
Make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
Model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
Year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
Engine HP,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
Engine Cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
Transmission Type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
Vehicle Style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway MPG,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
MSRP,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
engine_hp,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
engine_cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
transmission_type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
vehicle_style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway_mpg,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city_mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
msrp,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995

In [6]:
df.isnull().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
msrp                  0
dtype: int64

In [7]:
df.engine_hp = df.engine_hp.fillna(0)
df.engine_cylinders = df.engine_cylinders.fillna(0)

In [8]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
msrp                 0
dtype: int64

In [9]:
df['price'] = df.msrp

In [10]:
del df['msrp']
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
engine_hp,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
engine_cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
transmission_type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
vehicle_style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway_mpg,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city_mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
price,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995

In [11]:
df.transmission_type.mode()

0    AUTOMATIC
Name: transmission_type, dtype: object

In [12]:
numerical_cols = []
numerical_cols.append(list(df.dtypes[df.dtypes == 'int64'].index))
numerical_cols.append(list(df.dtypes[df.dtypes == 'float64'].index))

numerical_cols = numerical_cols[0] + numerical_cols[1]
numerical_cols

['year', 'highway_mpg', 'city_mpg', 'price', 'engine_hp', 'engine_cylinders']

In [13]:
df[numerical_cols].corr().unstack().sort_values(ascending=False)

year              year                1.000000
highway_mpg       highway_mpg         1.000000
engine_hp         engine_hp           1.000000
price             price               1.000000
city_mpg          city_mpg            1.000000
engine_cylinders  engine_cylinders    1.000000
highway_mpg       city_mpg            0.886829
city_mpg          highway_mpg         0.886829
engine_cylinders  engine_hp           0.774851
engine_hp         engine_cylinders    0.774851
                  price               0.650095
price             engine_hp           0.650095
engine_cylinders  price               0.526274
price             engine_cylinders    0.526274
year              engine_hp           0.338714
engine_hp         year                0.338714
highway_mpg       year                0.258240
year              highway_mpg         0.258240
                  price               0.227590
price             year                0.227590
year              city_mpg            0.198171
city_mpg          year                0.198171
year              engine_cylinders   -0.040708
engine_cylinders  year               -0.040708
city_mpg          price              -0.157676
price             city_mpg           -0.157676
highway_mpg       price              -0.160043
price             highway_mpg        -0.160043
engine_hp         highway_mpg        -0.415707
highway_mpg       engine_hp          -0.415707
city_mpg          engine_hp          -0.424918
engine_hp         city_mpg           -0.424918
city_mpg          engine_cylinders   -0.587306
engine_cylinders  city_mpg           -0.587306
highway_mpg       engine_cylinders   -0.614541
engine_cylinders  highway_mpg        -0.614541
dtype: float64

In [14]:
mean_price = df.price.mean()
df['above_average'] = np.where(df.price > mean_price, True, False)
# del df['price']
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
engine_hp,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
engine_cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
transmission_type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
vehicle_style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway_mpg,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city_mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
price,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995
above_average,True,True,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,False

In [15]:
#setup the framework 🥳
from sklearn.model_selection import train_test_split

In [16]:
df_train_full, df_test = train_test_split(df, test_size=0.20, random_state=42)
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=42)

len(df_train_full), len(df_train), len(df_test), len(df_val)

(9531, 7148, 2383, 2383)

In [17]:
y_train_full = df_train_full.above_average.values
y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test  = df_test.above_average.values

In [18]:
from sklearn.metrics import mutual_info_score

In [19]:
df_train.T

,3972,1997,5216,2805,11369,5213,527,4167,2793,9283,...,5299,10609,7695,11844,10853,9232,5710,11306,4414,10286
make,Mitsubishi,Kia,Lamborghini,Chevrolet,Pontiac,Mitsubishi,BMW,Cadillac,Chevrolet,GMC,...,Mercedes-Benz,Chevrolet,Toyota,GMC,Nissan,Toyota,Chevrolet,Hyundai,Mitsubishi,Ford
model,Endeavor,Borrego,Gallardo,Colorado,Vibe,Galant,5 Series,Escalade,Colorado,Sierra 1500 Classic,...,GLA-Class,TrailBlazer,Prius,Yukon Hybrid,Truck,Sienna,HHR,Veracruz,Expo,Taurus
year,2011,2009,2012,2016,2009,2011,2016,2016,2016,2007,...,2015,2007,2015,2013,1995,2016,2009,2012,1993,2015
engine_hp,225.0,276.0,570.0,200.0,158.0,160.0,240.0,420.0,305.0,295.0,...,355.0,395.0,134.0,332.0,153.0,266.0,260.0,260.0,136.0,365.0
engine_cylinders,6.0,6.0,10.0,4.0,4.0,4.0,4.0,8.0,6.0,8.0,...,4.0,8.0,4.0,8.0,6.0,6.0,4.0,6.0,4.0,6.0
transmission_type,AUTOMATIC,AUTOMATIC,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,...,AUTOMATED_MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,MANUAL,AUTOMATIC,MANUAL,AUTOMATIC,MANUAL,AUTOMATIC
vehicle_style,4dr SUV,4dr SUV,Convertible,Crew Cab Pickup,4dr Hatchback,Sedan,Sedan,4dr SUV,Crew Cab Pickup,Extended Cab Pickup,...,4dr SUV,4dr SUV,4dr Hatchback,4dr SUV,Extended Cab Pickup,Passenger Minivan,Wagon,4dr SUV,2dr Hatchback,Sedan
highway_mpg,19,21,20,27,26,30,34,21,24,17,...,29,17,48,23,17,25,29,22,26,25
city_mpg,15,17,12,20,20,21,23,15,17,13,...,23,13,51,20,14,18,21,17,19,17
price,33599,26245,248000,24990,20475,23999,50200,84145,32895,30255,...,48300,34885,26985,61960,2494,37655,25135,28345,2000,40220
above_average,False,False,True,False,False,False,True,True,False,False,...,True,False,False,True,False,False,False,False,False,False

In [20]:
def mutal_info(series):
    return mutual_info_score(df_train.above_average, series)

In [21]:
mi = df_train.apply(mutal_info)

In [22]:
mi.sort_values(ascending=False).round(2)

price                0.59
above_average        0.59
model                0.46
engine_hp            0.36
make                 0.24
engine_cylinders     0.12
vehicle_style        0.08
year                 0.07
city_mpg             0.06
highway_mpg          0.04
transmission_type    0.02
dtype: float64

In [23]:
# for safety delete the Target variable.
del df_train_full['above_average']
del df_train['above_average']
del df_val['above_average']
del df_test ['above_average']

del df_train_full['price']
del df_train['price']
del df_val['price']
del df_test ['price']

In [24]:
# WE are are going to do one hot encoding for this dataset
from sklearn.feature_extraction import DictVectorizer

train_dict = df_train.to_dict(orient='records')
dict_vector = DictVectorizer(sparse=False)
dict_vector.fit(train_dict)
X_train = dict_vector.transform(train_dict)

X_train

array([[1.500e+01, 6.000e+00, 2.250e+02, ..., 0.000e+00, 0.000e+00,
        2.011e+03],
       [1.700e+01, 6.000e+00, 2.760e+02, ..., 0.000e+00, 0.000e+00,
        2.009e+03],
       [1.200e+01, 1.000e+01, 5.700e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       ...,
       [1.700e+01, 6.000e+00, 2.600e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       [1.900e+01, 4.000e+00, 1.360e+02, ..., 0.000e+00, 0.000e+00,
        1.993e+03],
       [1.700e+01, 6.000e+00, 3.650e+02, ..., 1.000e+00, 0.000e+00,
        2.015e+03]])

In [25]:
## Training the model 

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [26]:
## Now check it with validation data 

val_dict = df_val.to_dict(orient='records')
X_val = dict_vector.transform(val_dict)

y_pred = model.predict(X_val)

## Checking the accuracy
from sklearn.metrics import accuracy_score

accuracy = np.round(accuracy_score(y_pred, y_val),2)
accuracy

0.93

In [27]:
features = list(df_train.dtypes.index.values)
features

['make',
 'model',
 'year',
 'engine_hp',
 'engine_cylinders',
 'transmission_type',
 'vehicle_style',
 'highway_mpg',
 'city_mpg']

In [28]:
orig_score = accuracy

for c in features: 
    subset = features.copy()
    subset.remove(c)
    
    train_dict = df_train[subset].to_dict(orient='records')
    
    dv = DictVectorizer(sparse=False)
    dv.fit(train_dict)
    
    X_train = dv.transform(train_dict)
    
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    
    val_dict = df_val[subset].to_dict(orient='records')
    X_val = dv.transform(val_dict)
    
    y_pred = model.predict(X_val)
    
    score = accuracy_score(y_val, y_pred)
    print(c, orig_score - score, score)

make 0.00973143096936635 0.9202685690306337
model 0.006374318086445729 0.9236256819135543
year -0.01838438942509435 0.9483843894250944
engine_hp 0.010990348300461639 0.9190096516995384
engine_cylinders -0.0074737725556021095 0.9374737725556022
transmission_type -0.011670163659252997 0.941670163659253
vehicle_style -0.007054133445237087 0.9370541334452371
highway_mpg -0.01208980276961813 0.9420898027696182
city_mpg -0.016286193873268906 0.946286193873269

In [29]:
## Ridge Regression 

df['price'] = np.log1p(df['price'])

In [30]:
#@ SPLITTING THE DATASET:
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=42)

In [31]:
#@ PREPARING THE DATASET:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [32]:
y_train_full = df_train_full.above_average.values
y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test  = df_test.above_average.values

In [33]:
# for safety delete the Target variable.
del df_train_full['above_average']
del df_train['above_average']
del df_val['above_average']
del df_test ['above_average']

del df_train_full['price']
del df_train['price']
del df_val['price']
del df_test ['price']

In [34]:
train_dict = df_train.to_dict(orient='records')

In [35]:

#@ VECTORIZING THE DATASET:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

X_train = dv.transform(train_dict)

val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)

In [36]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

for a in [0, 0.01, 0.1, 1, 10]:
    model = Ridge(alpha=a, solver="sag", random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_val)
    
    score = np.sqrt(mean_squared_error(y_val, y_pred))
    
    print(a, round(score, ))

/Users/ram/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0 0

/Users/ram/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0.01 0

/Users/ram/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0.1 0

/Users/ram/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

1 0
10 0

/Users/ram/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(